const data = {
  properties: [
    {
      category: 'Alquiler',
      code: '0001',
      name: 'Cangrejo, Apartamento, 50mts, 1 Hab, 1 Bañ, Linea blanca',
      image: '/images/p01/apt01-01.jpg',
      price: 500,
      squareMeters: 50,
      bedRooms: 1,
      bathRooms: 1,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0001',
    },
    {
      category: 'Alquiler',
      code: '0002',
      name: 'Obarrio, Apartamento, 60mts, 2 Hab, 1 Bañ, Amoblado',
      image: '/images/p02/apt02-01.jpg',
      price: 600,
      squareMeters: 60,
      bedRooms: 2,
      bathRooms: 1,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0002',
    },
    {
      category: 'Alquiler',
      code: '0003',
      name: 'Ave balboa, Apartamento, 70mts, 2 Hab, 2 Bañ, Linea blanca',
      image: '/images/p03/apt03-01.jpg',
      price: 700,
      squareMeters: 70,
      bedRooms: 2,
      bathRooms: 2,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0003',
    },
    {
      category: 'Alquiler',
      code: '0004',
      name: 'Cangrejo, Apartamento, 80mts, 3 Hab, 2 Bañ, Amoblado',
      image: '/images/p01/apt01-01.jpg',
      price: 800,
      squareMeters: 80,
      bedRooms: 3,
      bathRooms: 2,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0004',
    },
    {
      category: 'Venta',
      code: '1001',
      name: 'Marbella, Apartamento, 90mts, 2 Hab, 1 Bañ, Linea blanca',
      image: '/images/p02/apt02-01.jpg',
      price: 100000,
      squareMeters: 100,
      bedRooms: 2,
      bathRooms: 1,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0001',
    },
    {
      category: 'Venta',
      code: '1002',
      name: 'San francisco, Apartamento, 110mts, 2 Hab, 2 Bañ, Amoblado',
      image: '/images/p03/apt03-01.jpg',
      price: 110000,
      squareMeters: 110,
      bedRooms: 2,
      bathRooms: 2,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0002',
    },
    {
      category: 'Venta',
      code: '1003',
      name: 'Cangrejo, Apartamento, 50mts, 1 Hab, 1 Bañ, Linea blanca',
      image: '/images/p01/apt01-01.jpg',
      price: 120000,
      squareMeters: 120,
      bedRooms: 3,
      bathRooms: 2,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0003',
    },
    {
      category: 'Venta',
      code: '1004',
      name: 'Cangrejo, Apartamento, 50mts, 3 Hab, 3 Bañ, Amoblado',
      image: '/images/p02/apt02-01.jpg',
      price: 130000,
      squareMeters: 130,
      bedRooms: 3,
      bathRooms: 3,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0004',
    },
  ],
};

export default data;
