const data = {
  properties: [
    {
      name: 'Cangrejo, Apartamento, 50mts, 1 Hab, 1 Bañ, Linea blanca',
      slug: 'cangrejo-apartamento-50m2-1hab-1ba-lineablanca',
      category: 'alquiler',
      code: '0001',
      image: '/images/p01/apt01-01.jpg',
      price: 500,
      squareMeters: 50,
      bedRooms: 1,
      bathRooms: 1,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0001',
    },
    {
      name: 'Obarrio, Apartamento, 60mts, 2 Hab, 1 Bañ, Amoblado',
      slug: 'obarrio-apartamento-60m2-2hab-1ba-amoblado',
      category: 'alquiler',
      code: '0002',
      image: '/images/p02/apt02-01.jpg',
      price: 600,
      squareMeters: 60,
      bedRooms: 2,
      bathRooms: 1,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0002',
    },
    {
      name: 'Ave balboa, Apartamento, 70mts, 2 Hab, 2 Bañ, Linea blanca',
      slug: 'avebalboa-apartamento-70m2-2hab-2ba-lineablanca',
      category: 'alquiler',
      code: '0003',
      image: '/images/p03/apt03-01.jpg',
      price: 700,
      squareMeters: 70,
      bedRooms: 2,
      bathRooms: 2,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0003',
    },
    {
      name: 'Cangrejo, Apartamento, 80m2, 3 Hab, 2 Bañ, Amoblado',
      slug: 'cangrejo-apartamento-80m2-3hab-2ba-amoblado',
      category: 'alquiler',
      code: '0004',
      image: '/images/p01/apt01-01.jpg',
      price: 800,
      squareMeters: 80,
      bedRooms: 3,
      bathRooms: 2,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0004',
    },
    {
      name: 'Marbella, Apartamento, 90mts, 1 Hab, 1 Bañ, Linea blanca',
      slug: 'marbella-apartamento-90m2-1hab-1b-lineablanca',
      category: 'venta',
      code: '1001',
      image: '/images/p02/apt02-01.jpg',
      price: 100000,
      squareMeters: 90,
      bedRooms: 2,
      bathRooms: 1,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0001',
    },
    {
      name: 'San francisco, Apartamento, 100mts, 2 Hab, 2 Bañ, Amoblado',
      slug: 'sanfrancisco-apartamento-100m2-2hab-2ba-amoblado',
      category: 'venta',
      code: '1002',
      image: '/images/p03/apt03-01.jpg',
      price: 110000,
      squareMeters: 100,
      bedRooms: 2,
      bathRooms: 2,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0002',
    },
    {
      name: 'Cangrejo, Apartamento, 110mts, 3 Hab, 3 Bañ, Linea blanca',
      slug: 'cangrejo-apartamento-110m2-3hab-3ba-lineablanca',
      category: 'venta',
      code: '1003',
      image: '/images/p01/apt01-01.jpg',
      price: 120000,
      squareMeters: 110,
      bedRooms: 3,
      bathRooms: 2,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0003',
    },
    {
      name: 'Cangrejo, Apartamento, 120mts, 3 Hab, 3 Bañ, Amoblado',
      slug: 'cangrejo-apartamento-120m2-3hab-3ba-amoblado',
      category: 'venta',
      code: '1004',
      image: '/images/p02/apt02-01.jpg',
      price: 130000,
      squareMeters: 120,
      bedRooms: 3,
      bathRooms: 3,
      parkingLot: true,
      available: true,
      description: 'Descripcion 0004',
    },
  ],
};

export default data;
